# Generated by Django 4.2.4 on 2023-08-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='CityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Год')),
                ('income', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Ожидаемый доход')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_plan', to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='CityFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Год')),
                ('income', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Фактический доход')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_fact', to='app.city')),
            ],
        ),
    ]
