# Generated by Django 4.2.4 on 2023-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cityfact_income_alter_cityplan_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityfact',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Фактический доход'),
        ),
        migrations.AlterField(
            model_name='cityplan',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Ожидаемый доход'),
        ),
    ]
